# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

name: Dependency Updates and Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dependabot Updates
        uses: github/dependabot-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          directory: "/" # Location of package manifests
          package-manager: "auto"
          versioning-strategy: "increase" # Increase to always use the latest version
          commit-message: "chore: Bump dependencies" # Customize commit message as needed
          commit-prefix: "dependabot" # Customize commit prefix as needed
          create-pr: true # Specify to create pull requests
          schedule: "daily" # Adjust the update frequency as needed

  test:
    runs-on: ubuntu-latest
    needs: dependency-update
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
