name: Code Review Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  code-review-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Only run for pushes to main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check coding standards
        run: |
          npm run lint || true

      - name: Scan for security vulnerabilities
        run: |
          npm install snyk
          npx snyk test || true

      - name: Provide feedback
        id: feedback
        uses: actions/github-script@0.9.0
        with:
          script: |
            try {
              github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,  # Use issue number for push event
                body: 'Code review checks have been completed for this push. Please review the results.'
              });
            } catch (error) {
              console.error('Error creating comment:', error);
            }

  code-review-pull-request:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Only run for pull requests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check coding standards
        run: |
          npm run lint || true

      - name: Scan for security vulnerabilities
        run: |
          npm install snyk
          npx snyk test || true

      - name: Provide feedback
        id: feedback
        uses: actions/github-script@0.9.0
        with:
          script: |
            try {
              const { data: pullRequest } = await github.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number
              });

              github.issues.createComment({
                issue_number: pullRequest.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Code review checks have been completed for this pull request. Please review the results.'
              });
            } catch (error) {
              console.error('Error creating comment:', error);
            }

      - name: Debug feedback output
        run: |
          echo "${{ steps.feedback.outputs.body }}"

      - name: Save feedback to file
        run: |
          echo "${{ steps.feedback.outputs.body }}" > Codereview.txt || true

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add . || true
          git commit -m "Update code review " || true
          git push origin main || true
