name: Documentation Generation

on:
  push:
    branches:
      - main  

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 1: Install JSDoc and jsdoc-to-markdown
      - name: Install JSDoc and jsdoc-to-markdown
        run: npm install --save-dev jsdoc-to-markdown

      # Step 2: Generate documentation from comments in src/utils.js
      - name: Generate documentation
        run: |
          npx jsdoc-to-markdown ./src/utils.js > ./docs.md

       # Step 3: Check for changes and commit
      - name: Check for changes and commit
        run: |
          if git diff --quiet; then
            echo "No changes to commit. Exiting..."
            exit 0
          fi
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Generate documentation"

      # Step 4: Pull changes from main branch
      - name: Pull changes from main branch
        run: git pull origin main

      # Step 5: Push changes
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}

      
