name: Scheduled Tasks

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your task steps here
      - name: Run the app
        run: |
          #!/bin/bash
          node run.js
