name: Scheduled Tasks

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Add your task steps here
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Run the app
        run: |
          #!/bin/bash
          node run.js
