
#Workflow to automate a specific task or process
name: Generate Release Notes

on:
  push:
      branches:
      - main  

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Release Notes
        run: |
          echo "Generating release notes..."
          git log --oneline >> ./commit_messages.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Display Commit Logs"
          git push origin main


     